[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "drutils"
authors = [{name = "Daniel Sánchez", email = "danilacasito8@gmail.com"}]
dynamic = ["v0.1.8-Alpha", "My Multi Use Library"]
